# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from jieshuorpc import tts_pb2 as jieshuorpc_dot_tts__pb2


class TtsStub(object):
    """CosyVoice2 TTS service. Mirrors the former REST contract (tts_client.py): send a
    line of text (+ seed/speed and optional cloned-voice reference) and get back a WAV.

    Synthesize is SERVER-STREAMING: the WAV is sent as ordered byte chunks so the
    response size is bounded regardless of line length; the client concatenates them
    into the final WAV file.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_stream(
                '/jieshuorpc.Tts/Synthesize',
                request_serializer=jieshuorpc_dot_tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=jieshuorpc_dot_tts__pb2.AudioChunk.FromString,
                )


class TtsServicer(object):
    """CosyVoice2 TTS service. Mirrors the former REST contract (tts_client.py): send a
    line of text (+ seed/speed and optional cloned-voice reference) and get back a WAV.

    Synthesize is SERVER-STREAMING: the WAV is sent as ordered byte chunks so the
    response size is bounded regardless of line length; the client concatenates them
    into the final WAV file.
    """

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TtsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=jieshuorpc_dot_tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=jieshuorpc_dot_tts__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jieshuorpc.Tts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tts(object):
    """CosyVoice2 TTS service. Mirrors the former REST contract (tts_client.py): send a
    line of text (+ seed/speed and optional cloned-voice reference) and get back a WAV.

    Synthesize is SERVER-STREAMING: the WAV is sent as ordered byte chunks so the
    response size is bounded regardless of line length; the client concatenates them
    into the final WAV file.
    """

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/jieshuorpc.Tts/Synthesize',
            jieshuorpc_dot_tts__pb2.SynthesizeRequest.SerializeToString,
            jieshuorpc_dot_tts__pb2.AudioChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
